[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$Qsj5n/Neaw2BkPKes9bamw$5Wk0ExqRIPzDX/sqKzb.vRLRb51HKgRnquSE.5yaMSAviYxQy7QJglzQP8QYs8um0NUStQqMqgpvEjsnLAZ8LQ

