[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
host_port = 8000
db_host = db
db_port = 5432
postgres_user = odoo
postgres_password = odoo
postgres_db = postgres
admin_password = admin
admin_passwd = $pbkdf2-sha512$600000$uhfiHOO8t9ZaCwFgTMlZ6w$3WjyFczICAF1iB49jqLsjnxEnTThtvM..ywLu9wseSvMFwCl3M2QuPyUe0YvfQwOAaazEIEpMiBhLeRaOPyWbQ

