[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
admin_passwd = $pbkdf2-sha512$600000$WEuJ8T5nbM15TyklJGSs9Q$5tLgUbH/cLXBUZi1PqPP4jd.ichxvjFlymfVdAiJaOL6kgNMqBK7irxZaMo/tYdQrfYFcyh3Z.MpJh5Xi7W7vQ

